dynamic: "additive"
factors:
  - 4.0
  - 2.0
  - 1.0
  - 0.5
  - 0.25
#Gamble simulation parameters
gamble_simulation:
  fractals: [-407.0, -305.5, -241.5, -49.0, 50.0, 108.5, 210.5, 309.5, 440.5]
  # factals: [0.427, 0.583, 0.649, 0.841, 1.006, 1.184, 1.446, 1.739, 2.164]
  exclude_nobrainer: true
  mirror_gambles: true
  dynamic: additive #or multiplicative
